### PR TITLE
fix: add get_ref/get_mut/into_inner for noodles-vcf

### PR DESCRIPTION
**Pull request by holtgrewe**
Addresses the point raised in #210

### CODE REVIEW

**Comment by zaeleus** [comment]
Thanks!

**Comment by holtgrewe** [comment]
@zaeleus thanks. Could I get a crates release with this patch?

**Comment by zaeleus** [comment]
Yes, this is now released in noodles 0.55.0 / noodles-vcf 0.43.0.

**Comment by holtgrewe** [comment]
@zaeleus you're the best!

**Pull request merged**
